/*
 * CustomButton.hpp
 *
 *  Created on: Dec 17, 2020
 *      Author: andrey
 */

#ifndef GUI_INCLUDE_GUI_COMMON_CUSTOMBUTTONS_HPP_
#define GUI_INCLUDE_GUI_COMMON_CUSTOMBUTTONS_HPP_

extern "C" {
	#include "domain/use_cases/testing_use_case.h"
}

enum ButtonID {
	BUTTON_ID_MAKE_SCREENSHOT,
	BUTTON_ID_START_RECORDING,
	BUTTON_ID_STOP_RECORDING,
	BUTTON_ID_CONNECT_DEVICES,
	BUTTON_ID_DISCONNECT_DEVICES,
	BUTTON_ID_CLEAN,
	BUTTON_ID_START_TESTING,
	BUTTON_ID_PAUSE_TESTING,
	BUTTON_ID_STOP_TESTING
};

enum ButtonState {
	BUTTON_STATE_ENABLED,
	BUTTON_STATE_DISABLED
};

#endif /* GUI_INCLUDE_GUI_COMMON_CUSTOMBUTTONS_HPP_ */
